version: '3'

services:
  psql:
    image: postgres:latest
    container_name: server_psql
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db