spring:
  application:
    name: working-with-files
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_user
    password: test_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
